### ISSUE TITLE
Extensões / Themes Google Chrome & Config

### ISSUE THREAD

**Issue by adammacias** [adammacias/adammacias.github.io#23]
## Themes

- [Material Simple Dark Grey - Chrome Web Store](https://chrome.google.com/webstore/detail/material-simple-dark-grey/ookepigabmicjpgfnmncjiplegcacdbm)

### [Website Themes & Skins by Stylish | Userstyles.org](https://userstyles.org/)

```css
.list-card-cover.js-card-cover:hover {
      max-height: 10rem!important;
      background-size: contain!important; 
}

.list-card-cover.js-card-cover {
      max-height: 5rem!important;
      background-size: cover!important;     
}

/** https://chrome.google.com/webstore/detail/trello-card-numbers/kadpkdielickimifpinkknemjdipghaf **/
.list-header-num-cards {
      display: none!important;
}

// Alura

@import url('https://fonts.googleapis.com/css?family=Fira+Sans');

pre {
      font-family:"Fira Code Retina", 'Fira Sans', sans-serif!important;
      font-size: 18px;
      width: 150%;
}

.formattedText {
      font-family: 'Fira Sans', sans-serif!important;
      font-size: 24px!important;
      line-height: 41px!important;
}


// Gmail
.bAw {
      margin-right: 300px!important;
}

#yDmH0d > c-wiz > div .PYj7ue,
#yDmH0d > c-wiz > div > div {
    background: yellow!important;
}
```
